### ISSUE TITLE
工程如何编译？

### ISSUE THREAD

**Issue by hzm000000** [BeyondXinXin/KISS_Dicom_Viewer#1]
请问本项目是如何编译的，是使用cmake命令编译吗？编译出错

**Comment by hzm000000** [comment]
请问您用的是哪个qt版本？

**Comment by BeyondXinXin** [comment]
![image](https://user-images.githubusercontent.com/78600221/129443893-6a7ea9b2-8301-41c7-9451-a1ce27c52bb9.png)
