### ISSUE TITLE
你好，资源文件缺失了

### ISSUE THREAD

**Issue by libaineu2004** [BeyondXinXin/KISS_Dicom_Viewer#4]
你好。项目https://github.com/BeyondXinXin/Study/tree/master/Open_Browser/Source/01Business，这个路径里面的image资源文件夹怎么缺失了？

**Comment by BeyondXinXin** [comment]
https://github.com/BeyondXinXin/Study/blob/master/Open_Browser/CMakeLists.txt
179-182

```
set(02Resources
    Source/02Resources/style.qrc
    Source/02Resources/Image.qrc
    )
```

程序中只加载了两个qrc文件，其余的资源文件当时整理时候可能忘记删了

**Comment by BeyondXinXin** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！
