### ISSUE TITLE
关于CSDN博客的一些问题

### ISSUE THREAD

**Issue by CugAgo** [BeyondXinXin/KISS_Dicom_Viewer#6]
```
void RenderWidget::paintGL()
{
    QVTKOpenGLNativeWidget::paintGL();
    if (state_ == DrawCutLine && !cutting_points_.isEmpty()) {
        QPainter painter(this);
        DrawArea(cutting_points_, painter);
    }
}

void RenderWidget::mousePressEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton && state_ == DrawCutLine) {
        leftbtn_drag_ = true;
        cutting_points_.clear();
    }
    QVTKOpenGLNativeWidget::mousePressEvent(event);
}

void RenderWidget::mouseReleaseEvent(QMouseEvent *event)
{
    if (event->button() == Qt::LeftButton && state_ == DrawCutLine) {
        leftbtn_drag_ = false;
    }
    QVTKOpenGLNativeWidget::mouseReleaseEvent(event);
}

void RenderWidget::DrawArea(QList<QPointF> &pf, QPainter &painter)
{
    if (pf.length() < 1) {
        return;
    }

    QPainterPath path(pf[0]);
    for (int i = 1; i < pf.size(); ++i) {
        path.lineTo(pf[i]);
    }

    QPen pen;
    pen.setColor(Qt::green);
    painter.setPen(pen);
    painter.setBrush(QBrush(Qt::green, Qt::Dense4Pattern));
    painter.drawPath(path);
    painter.drawLine(pf[0], pf.last());
}
```
您好，我想请问一下这个代码中，RenderWidget具体是什么控件啊

**Comment by BeyondXinXin** [comment]
QVTKOpenGLWidget 或者 QVTKOpenGLNativeWidget 

代码都很早了不知道对不对的上

```cpp
class RenderWidget : public QVTKOpenGLNativeWidget
{
    Q_OBJECT
public:
    enum State
    {
        Normal,
        DrawCutLine,
        CutLineInside,
        CutLineOutside,
    };

public:
    explicit RenderWidget(QWidget *parent = nullptr);
    ~RenderWidget() override;

    void SetStyleState(const State &state);
    QPolygonF GetCuttingPolygon() const;

signals:
    void SgnCuttingLine(const int &type);

protected:
    void paintGL() override;
    void mousePressEvent(QMouseEvent *event) override;
    void mouseReleaseEvent(QMouseEvent *event) override;
    void mouseMoveEvent(QMouseEvent *event) override;
    void wheelEvent(QWheelEvent *event) override;

private:
    void drawArea(QList<QPointF> &pf, QPainter &painter);

private:
    QList<QPointF> cutting_points_ = QList<QPointF>();

    bool leftbtn_drag_ { false };
    State state_ { Normal };

    vtkNew<InteractorStyle> style_;
};
```

**Comment by CugAgo** [comment]
您好，我想问一下是先关闭了VTK窗口的交互功能，然后使用RenderWidget中重写的函数进行绘制，绘制完成再打开VTK交互类的交互吗，这个VTK的交互如果打开，是会覆盖RenderWidget重写的函数吗。

我目前使用VTK的窗口进行CT展示，然后想添加手动分割画label的功能，是直接在交互类中实现还是在类似RenderWidget中重写mousePressEvent这些事件实现好一点呢

另外，VTK：利用qt实现体绘制剪裁[](https://blog.csdn.net/a15005784320/article/details/119204925) 这个博客中的代码目前还有开源嘛，谢谢。

**Comment by BeyondXinXin** [comment]
> 您好，我想问一下是先关闭了VTK窗口的交互功能，然后使用RenderWidget中重写的函数进行绘制，绘制完成再打开VTK交互类的交互吗，这个VTK的交互如果打开，是会覆盖RenderWidget重写的函数吗。

一般接着传递即可，应该不冲突

> 我目前使用VTK的窗口进行CT展示，然后想添加手动分割画label的功能，是直接在交互类中实现还是在类似RenderWidget中重写mousePressEvent这些事件实现好一点呢

如果有很多自定义的交互还是单独实现交互类可能更合适一些

> 另外，VTK：利用qt实现体绘制剪裁 这个博客中的代码目前还有开源嘛，谢谢。

当时写博客核心代码都贴了，后来工程都删了。交互没啥就是纯工程化，核心是切割模型，我写的我记得就是最简单的遍历，很慢，只能很小的数据。

**Comment by BeyondXinXin** [comment]
不想自己反复造轮子，mitk 集成和调用的挺好的，可以用mitk

**Comment by CugAgo** [comment]
> 不想自己反复造轮子，mitk 集成和调用的挺好的，可以用mitk

太感谢了🫡🫡

**Comment by CugAgo** [comment]
> 不想自己反复造轮子，mitk 集成和调用的挺好的，可以用mitk

博主，我想再问一下MITK是使用德国那版还是中科院国内的版本好用一点呢？这部分集成调用，是cmake编译好他的源码后，我想用QT开发，是在QT中包含他的一些头文件吗，还是基于cmake修改他的源码，在他原来的基础上继续做开发呢，非常感谢！

另外如果方便的话，可以加个vx或者联系方式吗，我想做一些有偿咨询，感谢

**Comment by BeyondXinXin** [comment]
https://docs.mitk.org/2024.06/BlueBerryWorkbench.html
提供了一整套适合医疗软件客户端的开发框架。
公司项目就直接用他这一套，基于 Modules 和 Plugins ，99%的轮子都是现成的。
自己实现算法或者临时小项目用  https://docs.vtk.org/en/latest/api/python.html 
纯练手学习可以直接用 cmake + qt + vtk https://examples.vtk.org/site/Cxx/Qt/ShowEvent/

**Comment by CugAgo** [comment]
> https://docs.mitk.org/2024.06/BlueBerryWorkbench.html 提供了一整套适合医疗软件客户端的开发框架。 公司项目就直接用他这一套，基于 Modules 和 Plugins ，99%的轮子都是现成的。 自己实现算法或者临时小项目用 https://docs.vtk.org/en/latest/api/python.html 纯练手学习可以直接用 cmake + qt + vtk https://examples.vtk.org/site/Cxx/Qt/ShowEvent/
> 

谢谢，感谢
